ask/ask/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('qa.urls')),
    path('admin/', admin.site.urls),
]

ask/qa/urls.py
from django.urls import path
from django.contrib.auth.views import LogoutView

from . import views
from .models import Question, Answer, LikeDislike

app_name = 'qa'
urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('login', views.LoginView.as_view(), name='login'),
    path('signup', views.SignupView.as_view(), name='signup'),
    path('question/<int:pk>', views.QuestionDetailView.as_view(), name='question'),
    path('ask', views.QuestionAdd.as_view(), name='ask'),
    path('logout', LogoutView.as_view(), name='logout'),
    path('search', views.SearchView.as_view(), name='search'),
    path('delete_answer', views.AnswerDelete.as_view(), name='delete_answer'),
    path('delete_question', views.QuestionDelete.as_view(), name='delete_question'),
    path('question/<int:pk>/load_answers', views.LoadAnswers.as_view(), name='load_answers'),
    path('contacts', views.ContactsView.as_view(), name='contacts'),
    path('question/<int:pk>/like', views.VoteView.as_view(model=Question, vote_type=LikeDislike.LIKE),
         name='like_question'),
    path('question/<int:pk>/dislike', views.VoteView.as_view(model=Question, vote_type=LikeDislike.DISLIKE),
         name='dislike_question'),
    path('answer/<int:pk>/like', views.VoteView.as_view(model=Answer, vote_type=LikeDislike.LIKE),
         name='like_answer'),
    path('answer/<int:pk>/dislike', views.VoteView.as_view(model=Answer, vote_type=LikeDislike.DISLIKE),
         name='dislike_answer'),
]

ask/qa/models.py
from django.db import models
from django.contrib.auth.models import User
from django.contrib.contenttypes.models import ContentType
from django.contrib.contenttypes.fields import GenericForeignKey, GenericRelation


class LikeDislikeManager(models.Manager):
    use_for_related_fields = True

    def is_like_dislike(self, user, obj):
        try:
            return self.get(
                content_type=ContentType.objects.get_for_model(obj),
                object_id=obj.id,
                user=user
            ).vote
        except (TypeError, KeyError, LikeDislike.DoesNotExist):
            return 0

    def rating(self):
        return self.aggregate(models.Sum('vote')).get('vote__sum') or 0

    def set_like_or_dislike_or_remove(self, obj, user, vote_type):
        try:
            like_dislike = self.get(
                content_type=ContentType.objects.get_for_model(obj),
                object_id=obj.id,
                user=user
            )
            if like_dislike.vote is not vote_type:
                like_dislike.vote = vote_type
                like_dislike.save(update_fields=['vote'])
                return True
            else:
                like_dislike.delete()
                return False
        except (KeyError, LikeDislike.DoesNotExist):
            obj.votes.create(user=user, vote=vote_type)
            return True


class LikeDislike(models.Model):
    LIKE = 1
    DISLIKE = -1

    VOTES = (
        (LIKE, 'Нравится'),
        (DISLIKE, 'Не нравится'),
    )

    vote = models.SmallIntegerField(choices=VOTES)
    user = models.ForeignKey(User, on_delete=models.CASCADE)

    content_type = models.ForeignKey(ContentType, on_delete=models.CASCADE)
    object_id = models.PositiveIntegerField()
    content_object = GenericForeignKey()

    objects = LikeDislikeManager()


class QuestionManager(models.Manager):
    def new(self):
        return self.order_by('-added_at')

    def popular(self):
        return self.order_by('-rating', '-added_at')

    def my_questions(self, user):
        return self.filter(author=user).order_by('-added_at')

    def search(self, query_search):
        return self.filter(models.Q(title__icontains=query_search) | models.Q(text__icontains=query_search))


class Question(models.Model):
    objects = QuestionManager()
    title = models.CharField(max_length=255)
    text = models.TextField()
    added_at = models.DateTimeField(blank=True, auto_now_add=True)
    rating = models.IntegerField(default=0)
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    votes = GenericRelation(LikeDislike, related_query_name='questions')

    def __str__(self):
        return self.title

    def answers_new(self):
        return self.answer_set.order_by('-added_at')

    def answers_popular(self):
        return self.answer_set.order_by('-rating', '-added_at')

    @property
    def text_short(self):
        size = 200
        if len(self.text) > size:
            return f'{self.text[:size]}...'
        else:
            return self.text

    def update_rating(self):
        rating = self.votes.rating()
        self.rating = rating
        self.save(update_fields=['rating'])
        return rating


class Answer(models.Model):
    text = models.TextField()
    added_at = models.DateTimeField(blank=True, auto_now_add=True)
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    rating = models.IntegerField(default=0)
    votes = GenericRelation(LikeDislike, related_query_name='answers')

    def __str__(self):
        return self.text

    def update_rating(self):
        rating = self.votes.rating()
        self.rating = rating
        self.save(update_fields=['rating'])
        return rating

ask/qa/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth import authenticate

from .models import Answer
from .serializer import serialize_new_answer


class AskForm(forms.Form):
    title = forms.CharField(max_length=225, required=True, widget=forms.TextInput(attrs={
        'class': 'form-control',
        'id': 'title',
    }))
    text = forms.CharField(required=True, widget=forms.Textarea(attrs={
        'class': 'form-control',
        'id': 'text',
    }))


class AnswerForm(forms.Form):
    text = forms.CharField(required=True, widget=forms.Textarea(attrs={
        'class': 'form-control',
        'rows': 3,
    }))

    def save(self, question, user):
        text = self.cleaned_data.get('text')
        answer = Answer.objects.create(text=text, question=question, author=user)
        content = serialize_new_answer(answer, user)
        return content


class SignupForm(forms.Form):
    username = forms.CharField(max_length=100, required=True, widget=forms.TextInput(attrs={
        'class': 'form-control',
        'id': 'username',
    }))
    password = forms.CharField(required=True, widget=forms.PasswordInput(attrs={
        'class': 'form-control',
        'id': 'password'
    }))
    repeat_password = forms.CharField(required=True, widget=forms.PasswordInput(attrs={
        'class': 'form-control',
        'id': 'repeat_password'
    }))

    def clean(self):
        super().clean()
        username = self.cleaned_data.get('username')
        password = self.cleaned_data.get('password')
        repeat_password = self.cleaned_data.get('repeat_password')
        if User.objects.filter(username=username).exists():
            self.add_error('username', 'Пользователь с данным именем уже существует')
        if password != repeat_password:
            self.add_error('password', '')
            self.add_error('repeat_password', 'Пароли не совпадают')
        if len(password) < 8:
            self.add_error('password', '')
            self.add_error('repeat_password', 'Пароль должен быть не менее 8 символов')

    def save(self):
        user = User.objects.create_user(
            username=self.cleaned_data['username'],
            password=self.cleaned_data['password']
        )
        user.save()
        user = authenticate(**self.cleaned_data)
        return user


class AuthForm(forms.Form):
    username = forms.CharField(max_length=100, required=True, widget=forms.TextInput(attrs={
        'class': 'form-control',
        'id': 'username',
    }))
    password = forms.CharField(required=True, widget=forms.PasswordInput(attrs={
        'class': 'form-control',
        'id': 'password'
    }))

    def clean(self):
        super().clean()
        username = self.cleaned_data.get('username')
        if not User.objects.filter(username=username).exists():
            self.add_error('username', 'Пользователя с данным именем не существует')

ask/qa/views.py
from django.http import HttpResponse, HttpResponseRedirect, JsonResponse
from django.views import View
from django.shortcuts import render, get_object_or_404
from django.urls import reverse
from django.contrib.auth import authenticate, login
from django.core.paginator import Paginator

from .models import Question, Answer, LikeDislike
from .forms import AskForm, AnswerForm, SignupForm, AuthForm
from .serializer import serialize_answers, serialize_questions


class IndexView(View):
    sort_method = {
        'popular': lambda user: Question.objects.popular(),
        'new': lambda user: Question.objects.new(),
        'my_questions': lambda user: Question.objects.my_questions(user),
    }

    def get(self, request):
        if request.headers.get('X-Requested-With') == 'XMLHttpRequest':
            page = request.GET.get('page')
            sort_option = request.GET.get('sort_option')
            questions = self.sort_method[sort_option](request.user)
            paginate_by = 10
            paginator = Paginator(questions, paginate_by)
            page_obj = paginator.get_page(page)
            content = serialize_questions(page_obj, request.user)
            return JsonResponse(content, status=200)
        else:
            return render(request, 'index.html')


class QuestionDetailView(View):
    def get(self, request, pk):
        question = get_object_or_404(Question, pk=pk)
        form = AnswerForm()
        is_like_dislike = question.votes.is_like_dislike(request.user, question)
        is_like = 'active' if is_like_dislike == 1 else ''
        is_dislike = 'active' if is_like_dislike == -1 else ''
        return render(request, 'question.html', {
            'question': question,
            'rating': question.votes.rating(),
            'form': form,
            'url_like': reverse('qa:like_question', args=[question.id]),
            'url_dislike': reverse('qa:dislike_question', args=[question.id]),
            'is_like': is_like,
            'is_dislike': is_dislike,
        })

    def post(self, request, pk):
        question = get_object_or_404(Question, pk=pk)
        form = AnswerForm(request.POST)
        if form.is_valid():
            user = request.user
            if user.is_authenticated:
                content = form.save(question, user)
                return JsonResponse(content, status=200)
        return JsonResponse({'error': 'Validation error'}, status=400)


class QuestionAdd(View):
    def get(self, request):
        form = AskForm()
        return render(request, 'ask.html', {'form': form})

    def post(self, request):
        form = AskForm(request.POST)
        if form.is_valid():
            if request.user.is_authenticated:
                question = Question.objects.create(**form.cleaned_data, author=request.user)
                return HttpResponseRedirect(reverse('qa:question', args=(question.pk, )))
            else:
                form.add_error('text', 'Оставлять вопросы могут только авторизованные пользователи')
        return render(request, 'ask.html', {'form': form})


class SignupView(View):
    def get(self, request):
        form = SignupForm()
        return render(request, 'signup.html', {'form': form})

    def post(self, request):
        form = SignupForm(request.POST)
        if form.is_valid():
            user = form.save()
            if user is not None:
                login(request, user)
                return JsonResponse({'url': reverse('qa:index')}, status=200)
        return JsonResponse({'error': form.errors}, status=400)


class LoginView(View):
    def get(self, request):
        form = AuthForm()
        return render(request, 'login.html', {'form': form})

    def post(self, request):
        form = AuthForm(request.POST)
        if form.is_valid():
            user = authenticate(**form.cleaned_data)
            if user is not None:
                login(request, user)
                return JsonResponse({'url': reverse('qa:index')}, status=200)
        form.add_error('password', 'Неправильное имя пользователя или пароль')
        return JsonResponse({'error': form.errors}, status=400)


class SearchView(View):
    def get(self, request):
        if request.headers.get('X-Requested-With') == 'XMLHttpRequest':
            results = ''
            query_search = request.GET.get('search')
            if query_search:
                results = Question.objects.search(query_search)
            paginate_by = 10
            paginator = Paginator(results, paginate_by)
            page_number = request.GET.get('page')
            page_obj = paginator.get_page(page_number)
            content = serialize_questions(page_obj, request.user)
            return JsonResponse(content, status=200)
        else:
            return render(request, 'search.html')


class AnswerDelete(View):
    def post(self, request):
        user = request.user
        if user.is_authenticated:
            try:
                Answer.objects.get(
                    question=request.POST.get('question_id'),
                    author=user,
                    id=request.POST.get('answer_id')
                ).delete()
                return JsonResponse({}, status=200)
            except (KeyError, Answer.DoesNotExist):
                return JsonResponse({'error': 'DoesNotExist'}, status=400)
        return JsonResponse({'error': 'Is not authenticated'}, status=400)


class QuestionDelete(View):
    def post(self, request):
        user = request.user
        if user.is_authenticated:
            try:
                Question.objects.get(author=user, id=request.POST.get('id')).delete()
                return JsonResponse({}, status=200)
            except (KeyError, Question.DoesNotExist):
                return JsonResponse({'error': 'DoesNotExist'}, status=400)
        return JsonResponse({'error': 'Is not authenticated'}, status=400)


class LoadAnswers(View):
    sort_method = {
        'new': lambda pk: get_object_or_404(Question, pk=pk).answers_new(),
        'popular': lambda pk: get_object_or_404(Question, pk=pk).answers_popular(),
    }

    def get(self, request, pk):
        sort_option = request.GET.get('sort_option')
        paginate_by = 10
        answers = self.sort_method[sort_option](pk)
        paginator = Paginator(answers, paginate_by)
        page = request.GET.get('page')
        page_obj = paginator.get_page(page)
        content = serialize_answers(page_obj, request.user)
        return JsonResponse(content, status=200)


class ContactsView(View):
    def get(self, request):
        return render(request, 'contacts.html')


class VoteView(View):
    model = None
    vote_type = None

    def post(self, request, pk):
        user = request.user
        if user.is_authenticated:
            obj = get_object_or_404(self.model, pk=pk)
            result = LikeDislike.objects.set_like_or_dislike_or_remove(obj, user, self.vote_type)
            rating = obj.update_rating()
            return JsonResponse({
                'id': obj.id,
                'result': result,
                'rating': rating,
            }, status=200)
        else:
            return JsonResponse({'error': 'Is not authenticated'}, status=400)

ask/qa/templates/ask.html
{% extends 'block/base.html' %}
{% block title %}Новый вопрос{% endblock %}
{% block content %}
<div class="container">
    <div class="row justify-content-center">
        <div class="col-lg-9">
            <nav aria-label="breadcrumb">
                <ol class="breadcrumb">
                    <li class="breadcrumb-item"><a href="{% url 'qa:index' %}">Список вопросов</a></li>
                    <li class="breadcrumb-item active">Новый вопрос</li>
                </ol>
            </nav>
            <h2 class="text-center">Новый вопрос</h2>
            {% if user.is_authenticated %}
            {% if form.errors %}
            {% for error in form.non_field_errors %}
            <div class="alert alert-danger">
                <strong>{{ error|escape }}</strong>
            </div>
            {% endfor %}
            {% endif %}
            <form method="post">
                {% csrf_token %}
                <label class="form-label mt-2" for="title">Краткое описание вопроса</label>
                {{ form.title }}
                {% for error in form.title.errors %}
                <div class="alert alert-danger py-1 px-2 my-2">
                    <strong>{{ error|escape }}</strong>
                </div>
                {% endfor %}
                <label class="form-label mt-2" for="text">Ваш вопрос</label>
                {{ form.text }}
                {% for error in form.text.errors %}
                <div class="alert alert-danger py-1 px-2 my-2">
                    <strong>{{ error|escape }}</strong>
                </div>
                {% endfor %}
                <button type="submit" class="btn btn-primary mt-3">Отправить</button>
            </form>
            {% else %}
            <p>Чтобы оставить новый вопрос, необходимо
                <a href="{% url 'qa:login' %}">авторизоваться</a> или
                <a href="{% url 'qa:signup' %}">зарегистрироваться</a>
            </p>
            {% endif %}
        </div>
    </div>
</div>
{% endblock %}

ask/qa/templates/contacts.html
{% extends 'block/base.html' %}
{% block title %}Контакты{% endblock %}
{% block content %}
<div class="container">
    <div class="row justify-content-center">
        <div class="col-lg-9">
            <nav aria-label="breadcrumb">
                <ol class="breadcrumb">
                    <li class="breadcrumb-item"><a href="{% url 'qa:index' %}">Список вопросов</a></li>
                    <li class="breadcrumb-item active">Контакты</li>
                </ol>
            </nav>
            <div class="card my-3">
                <div class="card-body d-flex">
                    <p class="card-title lead w-25">Email:</p>
                    <p class="card-title lead">titov281@yandex.ru</p>
                </div>
            </div>
            <div class="card my-3">
                <div class="card-body d-flex">
                    <p class="card-title lead w-25">Github:</p>
                    <a class="card-title lead text-decoration-none" href="https://github.com/Leonid-T">github.com/Leonid-T</a>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

ask/qa/templates/index.html
{% extends 'block/base.html' %}
{% block title %}Question-Ask{% endblock %}
{% block content %}
<div class="container">
    <div class="row justify-content-center">
        <div class="col-lg-9">
            <ul id="sortOption" class="nav nav-tabs">
                <li class="nav-item">
                    <button id="new" class="nav-link active" onclick="changeOption('new')">Новые</button>
                </li>
                <li class="nav-item">
                    <button id="popular" class="nav-link" onclick="changeOption('popular')">Популярные</button>
                </li>
                {% if user.is_authenticated %}
                <li class="nav-item">
                    <button id="my_questions" class="nav-link" onclick="changeOption('my_questions')">Мои вопросы</button>
                </li>
                {% endif %}
            </ul>
            <div id="questions"></div>
            <nav class="d-flex justify-content-center mt-3 mb-1">
                <ul id="paginator" class="pagination"></ul>
            </nav>
        </div>
    </div>
</div>
{% endblock %}
{% block script %}
{% load static %}
<script src="{% static 'scripts/csrftoken.js' %}" defer></script>
<script src="{% static 'scripts/index.js' %}" defer></script>
<script src="{% static 'scripts/like_dislike.js' %}" defer></script>
{% endblock %}

ask/qa/templates/login.html
{% extends 'block/base.html' %}
{% block title %}Авторизация{% endblock %}
{% block content %}
<div class="container my-auto">
    <div class="row justify-content-center">
        <div class="col-lg-4">
            <h2 class="text-center">Авторизация</h2>
            <form class="needs-validation" method="post" action="{% url 'qa:login' %}">
                {% csrf_token %}
                <label class="form-label mt-2" for="username">Имя пользователя</label>
                {{ form.username }}
                <div class="invalid-feedback"></div>
                <label class="form-label mt-2" for="password">Пароль</label>
                {{ form.password }}
                <div class="invalid-feedback"></div>
                <button type="submit" class="btn btn-primary mt-3">Войти</button>
            </form>
        </div>
    </div>
</div>
{% endblock %}
{% block script %}
{% load static %}
<script src="{% static 'scripts/auth.js' %}" defer></script>
{% endblock %}

ask/qa/templates/question.html
{% extends 'block/base.html' %}
{% block title %}{{ question.title }}{% endblock %}
{% block content %}
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-lg-9">
                <nav aria-label="breadcrumb">
                    <ol class="breadcrumb">
                        <li class="breadcrumb-item"><a href="{% url 'qa:index' %}">Список вопросов</a></li>
                        <li class="breadcrumb-item active">{{ question.title }}</li>
                    </ol>
                </nav>
                <div class="card">
                    <div class="card-body">
                        <div class="d-flex justify-content-between">
                            <div class="d-flex">
                                <h3 class="card-title">{{ question.title }}</h3>
                                <h6 class="card-subtitle mt-2 mx-3 text-muted">{{ question.author }}</h6>
                            </div>
                            {% if user == question.author %}
                            <form method="post">
                            {% csrf_token %}
                            <button type="button" class="btn-close d-flex" onclick="AjaxRemoveQuestion('{% url 'qa:delete_question' %}', {{ question.id }}, '{% url 'qa:index' %}')" aria-label="Delete"></button>
                            </form>
                            {% endif %}
                        </div>
                        <p class="card-text my-3">{{ question.text }}</p>
                    </div>
                    <div class="d-flex justify-content-between px-3">
                        <time class="text-muted"><small>{{ question.added_at }}</small></time>
                        <div class="d-flex">
                            <h5 id="rating_{{ question.id }}" class="mx-2">{{ rating }}</h5>
                            <button id="like_{{ question.id }}" class="like mx-2 {{ is_like }}" onclick="like('{{ url_like }}')"></button>
                            <button id="dislike_{{ question.id }}" class="dislike {{ is_dislike }}" onclick="dislike('{{ url_dislike }}')"></button>
                        </div>
                    </div>
                </div>
                <h4 class="my-3">Ответы</h4>
                <div class="card my-3">
                    <h5 class="card-header">Оставьте свой ответ</h5>
                    <div class="card-body">
                        {% if user.is_authenticated %}
                        <form id="answer_form" method="post">
                            {% csrf_token %}
                            {{ form.text }}
                            <button type="submit" class="btn btn-primary mt-3">Отправить</button>
                        </form>
                        {% else %}
                        <p class="card-text">Для ответа на вопрос необходимо
                            <a href="{% url 'qa:login' %}">авторизоваться</a> или
                            <a href="{% url 'qa:signup' %}">зарегистрироваться</a>
                        </p>
                        {% endif %}
                    </div>
                </div>
                <ul id="sortOption" class="nav nav-tabs">
                    <li class="nav-item">
                        <button id="new" class="nav-link active" onclick="changeOption('new')">Новые</button>
                    </li>
                    <li class="nav-item">
                        <button id="popular" class="nav-link" onclick="changeOption('popular')">Популярные</button>
                    </li>
                </ul>
                <div id="answers"></div>
            </div>
        </div>
    </div>
{% endblock %}
{% block script %}
{% load static %}
<script src="{% static 'scripts/csrftoken.js' %}" defer></script>
<script src="{% static 'scripts/question.js' %}" defer></script>
<script src="{% static 'scripts/like_dislike.js' %}" defer></script>
{% endblock %}

ask/qa/templates/search.html
{% extends 'block/base.html' %}
{% block title %}Поиск{% endblock %}
{% block content %}
<div class="container">
    <div class="row justify-content-center">
        <div class="col-lg-9">
            <nav aria-label="breadcrumb">
                <ol class="breadcrumb">
                    <li class="breadcrumb-item"><a href="{% url 'qa:index' %}">Список вопросов</a></li>
                    <li class="breadcrumb-item active">Поиск</li>
                </ol>
            </nav>
            <h2 class="text-center my-3">Результаты поиска</h2>
            <p class="lead">Найдено вопросов: <span id="searchCount"></span></p>
            <div id="questions"></div>
            <nav class="d-flex justify-content-center mt-3 mb-1">
                <ul id="paginator" class="pagination"></ul>
            </nav>
        </div>
    </div>
</div>
{% endblock %}
{% block script %}
{% load static %}
<script src="{% static 'scripts/csrftoken.js' %}" defer></script>
<script src="{% static 'scripts/index.js' %}" defer></script>
<script src="{% static 'scripts/like_dislike.js' %}" defer></script>
{% endblock %}

ask/qa/templates/signup.html
{% extends 'block/base.html' %}
{% block title %}Регистрация{% endblock %}
{% block content %}
<div class="container my-auto">
    <div class="row justify-content-center">
        <div class="col-lg-4">
            {% if form.errors %}
                {% for error in form.non_field_errors %}
                <div class="alert alert-danger">
                    <strong>{{ error|escape }}</strong>
                </div>
                {% endfor %}
            {% endif %}
            <h2 class="text-center">Регистрация</h2>
            <form class="needs-validation" method="post" action="{% url 'qa:signup' %}">
                {% csrf_token %}
                <label class="form-label mt-2" for="username">Имя пользователя</label>
                {{ form.username }}
                <div class="invalid-feedback"></div>
                <label class="form-label mt-2" for="password">Пароль</label>
                {{ form.password }}
                <div class="invalid-feedback"></div>
                <label class="form-label mt-2" for="repeat_password">Повторите пароль</label>
                {{ form.repeat_password }}
                <div class="invalid-feedback"></div>
                <button type="submit" class="btn btn-primary mt-3">Регистрация</button>
            </form>
        </div>
    </div>
</div>
{% endblock %}
{% block script %}
{% load static %}
<script src="{% static 'scripts/auth.js' %}" defer></script>
{% endblock %}